[package]
name = "blonder"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
cgmath = "0.16.1"
gl = "0.10.0"
glfw = "0.61.0"
image = "0.19.0"
tobj = "0.1.6"
num = "0.2.0"
rand = "0.5.5"
log = "0.4.29"
fern = "0.7.1"
thiserror = "2.0.17"
anyhow = "1.0.100"
humantime = "2.3.0"
rusttype = "0.9.3"
